require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SubsrcibingplansController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Subsrcibingplan. As you add validations to Subsrcibingplan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubsrcibingplansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all subsrcibingplans as @subsrcibingplans" do
      subsrcibingplan = Subsrcibingplan.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:subsrcibingplans)).to eq([subsrcibingplan])
    end
  end

  describe "GET #show" do
    it "assigns the requested subsrcibingplan as @subsrcibingplan" do
      subsrcibingplan = Subsrcibingplan.create! valid_attributes
      get :show, params: {id: subsrcibingplan.to_param}, session: valid_session
      expect(assigns(:subsrcibingplan)).to eq(subsrcibingplan)
    end
  end

  describe "GET #new" do
    it "assigns a new subsrcibingplan as @subsrcibingplan" do
      get :new, params: {}, session: valid_session
      expect(assigns(:subsrcibingplan)).to be_a_new(Subsrcibingplan)
    end
  end

  describe "GET #edit" do
    it "assigns the requested subsrcibingplan as @subsrcibingplan" do
      subsrcibingplan = Subsrcibingplan.create! valid_attributes
      get :edit, params: {id: subsrcibingplan.to_param}, session: valid_session
      expect(assigns(:subsrcibingplan)).to eq(subsrcibingplan)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Subsrcibingplan" do
        expect {
          post :create, params: {subsrcibingplan: valid_attributes}, session: valid_session
        }.to change(Subsrcibingplan, :count).by(1)
      end

      it "assigns a newly created subsrcibingplan as @subsrcibingplan" do
        post :create, params: {subsrcibingplan: valid_attributes}, session: valid_session
        expect(assigns(:subsrcibingplan)).to be_a(Subsrcibingplan)
        expect(assigns(:subsrcibingplan)).to be_persisted
      end

      it "redirects to the created subsrcibingplan" do
        post :create, params: {subsrcibingplan: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Subsrcibingplan.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved subsrcibingplan as @subsrcibingplan" do
        post :create, params: {subsrcibingplan: invalid_attributes}, session: valid_session
        expect(assigns(:subsrcibingplan)).to be_a_new(Subsrcibingplan)
      end

      it "re-renders the 'new' template" do
        post :create, params: {subsrcibingplan: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested subsrcibingplan" do
        subsrcibingplan = Subsrcibingplan.create! valid_attributes
        put :update, params: {id: subsrcibingplan.to_param, subsrcibingplan: new_attributes}, session: valid_session
        subsrcibingplan.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested subsrcibingplan as @subsrcibingplan" do
        subsrcibingplan = Subsrcibingplan.create! valid_attributes
        put :update, params: {id: subsrcibingplan.to_param, subsrcibingplan: valid_attributes}, session: valid_session
        expect(assigns(:subsrcibingplan)).to eq(subsrcibingplan)
      end

      it "redirects to the subsrcibingplan" do
        subsrcibingplan = Subsrcibingplan.create! valid_attributes
        put :update, params: {id: subsrcibingplan.to_param, subsrcibingplan: valid_attributes}, session: valid_session
        expect(response).to redirect_to(subsrcibingplan)
      end
    end

    context "with invalid params" do
      it "assigns the subsrcibingplan as @subsrcibingplan" do
        subsrcibingplan = Subsrcibingplan.create! valid_attributes
        put :update, params: {id: subsrcibingplan.to_param, subsrcibingplan: invalid_attributes}, session: valid_session
        expect(assigns(:subsrcibingplan)).to eq(subsrcibingplan)
      end

      it "re-renders the 'edit' template" do
        subsrcibingplan = Subsrcibingplan.create! valid_attributes
        put :update, params: {id: subsrcibingplan.to_param, subsrcibingplan: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested subsrcibingplan" do
      subsrcibingplan = Subsrcibingplan.create! valid_attributes
      expect {
        delete :destroy, params: {id: subsrcibingplan.to_param}, session: valid_session
      }.to change(Subsrcibingplan, :count).by(-1)
    end

    it "redirects to the subsrcibingplans list" do
      subsrcibingplan = Subsrcibingplan.create! valid_attributes
      delete :destroy, params: {id: subsrcibingplan.to_param}, session: valid_session
      expect(response).to redirect_to(subsrcibingplans_url)
    end
  end

end
